#nullable enable
// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using System.Security.Cryptography;
using System.Text;

namespace SqlQueryAnalyzer.Utilities;

/// <summary>
/// Generates cache keys for queries and analysis results.
/// Ensures consistent key generation across the application.
/// Keys are deterministic: same input always produces same key.
/// </summary>
public class QueryCacheKeyGenerator
{
    private const string KeyPrefix = "sqlanalyzer:";
    private const string QueryHashPrefix = "query:";
    private const string ResultHashPrefix = "result:";

    /// <summary>
    /// Generates a cache key for a query.
    /// Uses SHA256 hash of normalized query for efficient key generation.
    /// </summary>
    public string GenerateQueryKey(string query)
    {
        if (string.IsNullOrEmpty(query))
            throw new ArgumentException("Query cannot be null or empty");

        var normalized = NormalizeForHashing(query);
        var hash = ComputeHash(normalized);
        return $"{KeyPrefix}{QueryHashPrefix}{hash}";
    }

    /// <summary>
    /// Generates a cache key for analysis results.
    /// Links result key to query key for quick lookups.
    /// </summary>
    public string GenerateResultKey(string query)
    {
        if (string.IsNullOrEmpty(query))
            throw new ArgumentException("Query cannot be null or empty");

        var normalized = NormalizeForHashing(query);
        var hash = ComputeHash(normalized);
        return $"{KeyPrefix}{ResultHashPrefix}{hash}";
    }

    /// <summary>
    /// Generates a cache key for analysis metadata.
    /// Used for storing analysis configuration and settings.
    /// </summary>
    public string GenerateMetadataKey(string query, Dictionary<string, string>? parameters = null)
    {
        var builder = new StringBuilder(query);

        if (parameters != null)
        {
            foreach (var param in parameters.OrderBy(p => p.Key))
            {
                builder.Append("|");
                builder.Append(param.Key);
                builder.Append("=");
                builder.Append(param.Value);
            }
        }

        var normalized = NormalizeForHashing(builder.ToString());
        var hash = ComputeHash(normalized);
        return $"{KeyPrefix}meta:{hash}";
    }

    /// <summary>
    /// Generates a batch cache key for multiple queries.
    /// Useful for caching batch analysis results.
    /// </summary>
    public string GenerateBatchKey(string[] queries)
    {
        if (queries == null || queries.Length == 0)
            throw new ArgumentException("Query list cannot be null or empty");

        var combined = string.Join("|", queries.Select(q => ComputeHash(NormalizeForHashing(q))));
        var hash = ComputeHash(combined);
        return $"{KeyPrefix}batch:{hash}";
    }

    /// <summary>
    /// Normalizes query for consistent hashing.
    /// Removes whitespace variations that don't affect query logic.
    /// </summary>
    private string NormalizeForHashing(string input)
    {
        // Convert to uppercase for case-insensitive hashing
        var normalized = input.ToUpperInvariant();

        // Remove excess whitespace
        normalized = System.Text.RegularExpressions.Regex.Replace(normalized, @"\s+", " ");

        // Trim leading/trailing spaces
        normalized = normalized.Trim();

        return normalized;
    }

    /// <summary>
    /// Computes SHA256 hash of input string.
    /// Returns hex-encoded hash.
    /// </summary>
    private string ComputeHash(string input)
    {
        using var sha256 = SHA256.Create();
        var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(input));

        // Convert to hex string for cache key compatibility
        var builder = new StringBuilder();
        foreach (var b in hashedBytes)
        {
            builder.Append(b.ToString("x2"));
        }

        return builder.ToString();
    }

    /// <summary>
    /// Validates if a key was generated by this generator.
    /// Checks for proper prefix and format.
    /// </summary>
    public bool IsValidCacheKey(string key)
    {
        if (string.IsNullOrEmpty(key))
            return false;

        return key.StartsWith(KeyPrefix) &&
               (key.Contains(QueryHashPrefix) ||
                key.Contains(ResultHashPrefix) ||
                key.Contains("meta:") ||
                key.Contains("batch:"));
    }

    /// <summary>
    /// Extracts query hash from a cache key.
    /// Useful for debugging and statistics.
    /// </summary>
    public string? ExtractHashFromKey(string key)
    {
        if (!IsValidCacheKey(key))
            return null;

        var parts = key.Split(":");
        return parts.Length > 2 ? parts.Last() : null;
    }

    /// <summary>
    /// Gets the type of cache key.
    /// </summary>
    public CacheKeyType GetKeyType(string key)
    {
        if (key.Contains(QueryHashPrefix))
            return CacheKeyType.Query;
        if (key.Contains(ResultHashPrefix))
            return CacheKeyType.Result;
        if (key.Contains("meta:"))
            return CacheKeyType.Metadata;
        if (key.Contains("batch:"))
            return CacheKeyType.Batch;

        return CacheKeyType.Unknown;
    }
}

/// <summary>
/// Type of cache key.
/// </summary>
public enum CacheKeyType
{
    Query,
    Result,
    Metadata,
    Batch,
    Unknown
}
